theme: jekyll-theme-midnight
include:
  - "assets"
github:
  is_project_page: false

languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: French
  en: English
email: lyrz-games@gmail.com
